### ISSUE TITLE
Could you make the dataset public available ?

### ISSUE THREAD

**Issue by huangchaoxing** [junyuchen245/Unsuprevised_Seg_via_CNN#4]
Hi

Thanks for making the code open-sourced. 

May I ask if you can make your training data public available ?

Thank you

**Comment by ningscapr** [comment]
Same request. Is it possible we can get your training data?

**Comment by junyuchen245** [comment]
Hi guys,

I'm afraid that I cannot share the data with you, as our simulation is based off of the 4-D NURBS-based Cardiac-Torso (XCAT) phantom. This digital phantom was licensed by Dr. Tsui in our group at Johns Hopkins, and Dr. Segars at Duke University. So, I’m afraid that I don’t have the right to distribute this phantom data without you having a license. To find more information on how to obtain a license, you can either visit our lab website:

https://www.hopkinsmedicine.org/radiology/research/divisions/radiological-physics/research/projects/imaging-simulation-computer-phantoms.html

or Dr. Segars’s lab website: 

https://olv.duke.edu/technologies/4d-extended-cardiac-torso-xcat-phantom-version-2-0/

and please keep in mind that a licensing fee will be required.

Junyu
