### ISSUE TITLE
Run `Mode4`

### ISSUE THREAD

**Issue by TNA8** [junyuchen245/Unsuprevised_Seg_via_CNN#8]
Thanks for your great work.

I want to run `Mode4` described in your paper.
I ever tried to run other modes successfully.
Could you help me with how to run the `Mode4` step by step?

Thanks in advance.

**Comment by junyuchen245** [comment]
Apologies for the delayed response. To run mode 4, all you need is simply initialize the model with two loss functions:
https://github.com/junyuchen245/Unsuprevised_Seg_via_CNN/blob/88c7d4581b1c47ee33da84b0daceaaf357b7f48a/Unsupervised_Seg/train.py#L65

Junyu
